#!/bin/bash
# create dummy files containing a message

MSG="SDO is down"
SEE='see'
LINK="sdo.gsfc.nasa.gov"

mkimg () {

    FN=$1
    W=$2
    H=$3

    let "MTX=$W/10"
    let "MTY=$H/3"
    let "MTS=$H/12"

    let "STX=7*$W/16"
    let "STY=5*$H/9"
    let "STS=$H/16"

    let "LTX=$W/10"
    let "LTY=2*$H/3"
    let "LTS=$H/16"

    pbmmake -black $W $H \
        | ppmlabel -color "#ff0000" \
                -x $MTX -y $MTY -size $MTS -text "$MSG" \
                -x $STX -y $STY -size $STS -text "$SEE" \
                -x $LTX -y $LTY -size $LTS -text "$LINK" \
        | ppmtobmp -bpp 24 -windows > $FN

}

mkimg f_131_170.bmp 170 170
mkimg f_131_340.bmp 340 340
mkimg f_131_510.bmp 510 510
mkimg f_131_680.bmp 680 680
mkimg f_193_170.bmp 170 170
mkimg f_193_340.bmp 340 340
mkimg f_193_510.bmp 510 510
mkimg f_193_680.bmp 680 680
mkimg f_211_170.bmp 170 170
mkimg f_211_193_171_170.bmp 170 170
mkimg f_211_193_171_340.bmp 340 340
mkimg f_211_193_171_510.bmp 510 510
mkimg f_211_193_171_680.bmp 680 680
mkimg f_211_340.bmp 340 340
mkimg f_211_510.bmp 510 510
mkimg f_211_680.bmp 680 680
mkimg f_304_170.bmp 170 170
mkimg f_304_340.bmp 340 340
mkimg f_304_510.bmp 510 510
mkimg f_304_680.bmp 680 680
mkimg latest_170_HMIB.bmp 170 170
mkimg latest_170_HMIIC.bmp 170 170
mkimg latest_340_HMIB.bmp 340 340
mkimg latest_340_HMIIC.bmp 340 340
mkimg latest_510_HMIB.bmp 510 510
mkimg latest_510_HMIIC.bmp 510 510
mkimg latest_680_HMIB.bmp 680 680
mkimg latest_680_HMIIC.bmp 680 680
